name: flutter_travel_10
description: A Flutter Ride Booking Application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1

  # Dependency Injection & Local Storage
  get_it: ^9.0.5
  shared_preferences: ^2.5.3

  # Maps & Location
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Device
  local_auth: ^2.3.0
  device_info_plus: ^12.1.0
  safe_device: ^1.2.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_svg: ^2.2.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true