// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXGvYyJ0CMilCoHlCkpFisa4Q0MGqT_-Y',
    appId: '1:93529948514:web:512012a8d3846272a1ac3b',
    messagingSenderId: '93529948514',
    projectId: 'the-happy-car-project',
    authDomain: 'the-happy-car-project.firebaseapp.com',
    storageBucket: 'the-happy-car-project.firebasestorage.app',
    measurementId: 'G-3H7DMYEZH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqIWW_sGG-x7FTaqjyZvauGfVfFTcUyUo',
    appId: '1:93529948514:android:7344008e4b282cd9a1ac3b',
    messagingSenderId: '93529948514',
    projectId: 'the-happy-car-project',
    storageBucket: 'the-happy-car-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArLia8ow0xaDYZrB0Zx-JEVtItREzVUWc',
    appId: '1:93529948514:ios:fe6632956a9de327a1ac3b',
    messagingSenderId: '93529948514',
    projectId: 'the-happy-car-project',
    storageBucket: 'the-happy-car-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterNodjs10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArLia8ow0xaDYZrB0Zx-JEVtItREzVUWc',
    appId: '1:93529948514:ios:fe6632956a9de327a1ac3b',
    messagingSenderId: '93529948514',
    projectId: 'the-happy-car-project',
    storageBucket: 'the-happy-car-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterNodjs10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXGvYyJ0CMilCoHlCkpFisa4Q0MGqT_-Y',
    appId: '1:93529948514:web:c8bd0e3c6994a0f5a1ac3b',
    messagingSenderId: '93529948514',
    projectId: 'the-happy-car-project',
    authDomain: 'the-happy-car-project.firebaseapp.com',
    storageBucket: 'the-happy-car-project.firebasestorage.app',
    measurementId: 'G-SPF26NN6F5',
  );
}
